name: flutter_base
description: flutter基础封装，集成下拉刷新上拉加载，异步网络请求等

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.0.3 #toast
  dio: ^2.1.13 #网络请求框架
  provider: ^3.0.0+1 #状态管理
  webview_flutter: ^0.3.16 #安卓webview增加滚动监听
#  url_launcher: ^5.1.4 #用于在移动平台中启动URL。支持iOS和Android。
  rxdart: ^0.22.3 # https://github.com/ReactiveX/rxdart
  sqflite: ^1.1.3 #数据库 https://github.com/tekartik/sqflite
  pull_to_refresh: ^1.5.7
  cached_network_image: ^1.1.3 #用于显示来自Internet的图像并将它们保存在缓存目录中。
  shared_preferences: ^0.5.3+4 #shared_preferences本地存储
  flustars: ^0.2.6+1 #该库包含SpUtil（单例"同步" SharedPreferences 工具类），ScreenUtil（屏幕适配），WidgetUtil（Widget渲染监听，获取Widget宽高，在屏幕上的坐标）。 https://github.com/Sky24n/flustars
#  common_utils: ^1.1.3  #该库包含TimerUtil（倒计时，定时任务），TimelineUtil（时间轴），DateUtil（日期格式化），RegexUtil（正则验证手机号，身份证，邮箱等等），RegexUtil（正则验证手机号，身份证，邮箱等等），NumUtil（保留x位小数, 精确加、减、乘、除, 防止精度丢失），MoneyUtil（元转分，分转元），ObjectUtil（判空），LogUtil（简单封装打印日志）。 https://github.com/Sky24n/common_utils
  azlistview: ^0.1.2 #AzListView，Flutter 城市列表，联系人列表，自定义Header，索引，悬停效果。
  random_string: ^1.1.0
  image_picker: ^0.6.1+10 #图片选择或者视频选择
  intl: ^0.15.7 #国际化
  flukit: ^1.0.2 #轮播图
  qrscan: ^0.2.10 #扫一扫
  audioplayers: ^0.13.3 #音乐播放
  path_provider: ^1.1.3
  permission_handler: '^4.0.0'
#  amap_location: #高德地图


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - jsons/city.json
    - images/ico_network_error.png
    - images/ico_data_empty.png
    - images/icon_back_white.png
    - images/icon_back_black.png
    - images/ic_loading_white_01.png
    - images/ic_loading_white_02.png
    - images/ic_loading_white_03.png
    - images/ic_loading_white_04.png
    - images/ic_loading_white_05.png
    - images/ic_loading_white_06.png
    - images/ic_loading_white_07.png
    - images/ic_loading_white_08.png
    - images/ic_loading_white_09.png
    - images/ic_loading_white_10.png
    - images/ic_loading_white_11.png
    - images/ic_loading_white_00.png
    - images/default_center_00000.png
    - images/default_center_00001.png
    - images/default_center_00002.png
    - images/default_center_00003.png
    - images/default_center_00004.png
    - images/default_center_00005.png
    - images/default_center_00006.png
    - images/default_center_00007.png
    - images/default_center_00008.png
    - images/default_center_00009.png
    - images/default_center_00010.png
    - images/default_center_00011.png
    - images/default_center_00012.png
    - images/default_center_00013.png
    - images/default_center_00014.png
    - images/default_center_00015.png
    - images/default_center_00016.png
    - images/default_center_00017.png
    - images/default_center_00018.png
    - images/default_center_00019.png
    - images/default_center_00020.png
    - images/default_center_00021.png
    - images/default_center_00022.png
    - images/default_center_00023.png
    - images/default_center_00024.png
    - images/default_center_00025.png
    - images/default_center_00026.png
    - images/default_center_00027.png
    - images/default_center_00028.png
    - images/default_center_00029.png
    - images/default_grey000.png
    - images/default_grey001.png
    - images/default_grey002.png
    - images/default_grey003.png
    - images/default_grey004.png
    - images/default_grey005.png
    - images/default_grey006.png
    - images/default_grey007.png
    - images/default_grey008.png
    - images/default_grey009.png
    - images/refresh_icon_header_00000.png
    - images/refresh_icon_header_00001.png
    - images/refresh_icon_header_00002.png
    - images/refresh_icon_header_00003.png
    - images/refresh_icon_header_00004.png
    - images/refresh_icon_header_00005.png
    - images/refresh_icon_header_00006.png
    - images/refresh_icon_header_00007.png
    - images/refresh_icon_header_00008.png
    - images/refresh_icon_header_00009.png
    - images/refresh_icon_header_00010.png
    - images/refresh_icon_header_00011.png
    - images/refresh_icon_header_00012.png
    - images/refresh_icon_header_00013.png
    - images/refresh_icon_header_00014.png
    - images/scroll_to_top_button.png
    - images/ico_logo.png
    - images/ico_start_top.png
    - images/ico_start_bg.png
    - images/ico_clear.png
    - images/ico_login_top.png
    - images/ico_pwd_show.png
    - images/ico_pwd_hide.png
    - images/ico_login_phone.png
    - images/ico_login_password.png
    - images/ico_login_code.png
    - images/ico_login_image_code.png
    - images/msg_box_succeed.png
    - images/msg_box_remind.png
    - images/pic_default_man.png
    - images/pic_default_secret.png
    - images/pic_default_woman.png
    - images/ic_arrow_smallgrey.png
    - images/ico_close.png
    - images/ico_item_select.png
    - images/ico_item_selected.png
    - images/ico_search_empty.png
    - images/ico_integral.png
    - images/ico_man.png
    - images/ico_woman.png
    - images/ico_redact_info.png
    - images/user_page_top_bg_01.png
    - images/user_page_top_bg_02.png
    - images/user_page_top_bg_03.png
    - images/ic_book.png
    - images/ic_music.png
    - images/ic_run.png
    - images/ic_notepad.png
    - images/ic_more_app.png
    - images/ico_add_blue.png
    - images/ico_hint_green.png
    - images/ico_up_white.png
    - images/user_page_top_bg_04.png
    - images/ico_pull_down.png
    - images/ico_tally_details_bg.png
    - images/ico_mine_history.png
    - images/ico_mine_message.png
    - images/ico_like.png
    - images/ico_dislike.png
    - images/ico_mine_project.png
    - images/ico_mine_msg.png
    - images/ico_rank_top.png
    - images/ico_rank_two.png
    - images/ico_rank_three.png
    - images/ico_paper_bg.png
    - images/ico_search_gray.png
    - images/ico_history_clear.png
    - images/ico_search_black.png
    - images/ico_music_default.png
    - images/ico_music_play_bg.png
    - images/ico_music_logo.png
    - images/ico_top_bg.png
    - images/ico_chat_robot.png
    - images/ic_chat_robot.png
    - images/ico_chat_voice.png
    - images/ico_chat_keyboard.png
    - images/ico_chat_no_emil.png
    - images/ico_chat_yes_emil.png
    - images/ico_chat_more.png
    - images/ico_chat_more_yes.png
    - images/ease_chatto_bg_normal.9.png
    - images/ease_chatfrom_bg_normal.9.png
    - images/emil/ee_1.png
    - images/emil/ee_2.png
    - images/emil/ee_3.png
    - images/emil/ee_4.png
    - images/emil/ee_5.png
    - images/emil/ee_6.png
    - images/emil/ee_7.png
    - images/emil/ee_8.png
    - images/emil/ee_9.png
    - images/emil/ee_10.png
    - images/emil/ee_11.png
    - images/emil/ee_12.png
    - images/emil/ee_13.png
    - images/emil/ee_14.png
    - images/emil/ee_15.png
    - images/emil/ee_16.png
    - images/emil/ee_17.png
    - images/emil/ee_18.png
    - images/emil/ee_19.png
    - images/emil/ee_20.png
    - images/emil/ee_21.png
    - images/emil/ee_22.png
    - images/emil/ee_23.png
    - images/emil/ee_24.png
    - images/emil/ee_25.png
    - images/emil/ee_26.png
    - images/emil/ee_27.png
    - images/emil/ee_28.png
    - images/emil/ee_29.png
    - images/emil/ee_30.png
    - images/emil/ee_31.png
    - images/emil/ee_32.png
    - images/emil/ee_33.png
    - images/emil/ee_34.png
    - images/emil/ee_35.png
    - images/ico_card_bg.png
    - images/ico_woman_white.png
    - images/ico_man_white.png